project:
  type: website
  preview:
    port: 3000
    browser: true
    watch-inputs: true
    navigate: true
  output-dir: docs
  render:
    - '*.qmd'

website:
  title: 'GPS Positioning: A Mathematical Perspective'
  navbar:
    tools:
      - icon: gitlab
        href: https://gitlab.com/naterrl15/the-fourth-sphere
    left:
      - href: ./code/index.html
        text: Code

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  warning: false
  message: false

jupyter: python3
